services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db